### ISSUE TITLE
PVnet 2.0 production [meta]

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/PVNet#12]
- [x] Upgrade to use datapipes #10 
- [x] make app
- [x] add end to end test to app
- [x] add logging
- [x] add diagram to readme
- [x] add test for app.py
- [x] make docker file #11 
- [x] make and release docker file one main #9 
- [x] https://github.com/openclimatefix/ocf-infrastructure/issues/243
- [x] https://github.com/openclimatefix/ocf-infrastructure/issues/244
- [x] compare pvnet 1.0 and pvnet 2.0
- [x] check robustness of pvnet 2.0
- [x] add pvnet 2.0 to adjuster

Current version of things are
- pvnet = 0.0.19
- api = 1.4.5
- metrics = 1.1.2

Future
- [ ] add gsp in-day work
- [ ] add pv system

**Comment by peterdudfield** [comment]
FYI @dfulu , feel to add other things here

**Comment by peterdudfield** [comment]
Ill close this for now
